# Generated by Django 5.0.1 on 2024-01-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_abonent', models.CharField(max_length=250, verbose_name='Абонент')),
                ('number', models.IntegerField()),
                ('tarif', models.CharField(max_length=250, verbose_name='тарифный план')),
                ('balance', models.IntegerField(default=0, verbose_name='обший баланс')),
                ('min', models.IntegerField(default=0, verbose_name='обший минута')),
                ('sms', models.IntegerField(default=0, verbose_name='обший смс')),
                ('in_min', models.IntegerField(default=0, verbose_name='минуты внутри сети')),
                ('vne_min', models.IntegerField(default=0, verbose_name='минуты вне сети')),
                ('in_sms', models.IntegerField(default=0, verbose_name='смс')),
                ('internet', models.IntegerField(default=0, verbose_name='интернет')),
            ],
            options={
                'verbose_name': 'Abonent',
                'verbose_name_plural': 'Abonents',
            },
        ),
    ]
