# Generated by Django 4.2.7 on 2024-01-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonent',
            options={'verbose_name': 'Абоненты', 'verbose_name_plural': 'Абоненты'},
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=21, upload_to=''),
            preserve_default=False,
        ),
    ]
